name: Apply Patches

on:
  workflow_dispatch: # allows manual trigger

jobs:
  apply-patches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main  # checkout main to create data branch from it

      - name: Create and push data branch if doesn't exist
        run: |
          git ls-remote --heads origin data || (git checkout -b data && git push origin data)

      - name: Checkout datacontributions branch
        uses: actions/checkout@v2
        with:
          ref: datacontributions  # checkout datacontributions branch for applying patches

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: | 
          npm install json-patch
          npm install simple-git 

      - name: Run script to apply patches
        run: node .github/scripts/apply-data-patches.js

      - name: Checkout data branch
        uses: actions/checkout@v2
        with:
          ref: data  # checkout data branch to commit changes

      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Commit changes
        run: |
          git add -A
          git commit -m "Apply patches from datacontributions branch"
          git push

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Apply patches from datacontributions branch"
          base: main  # PR will propose to merge into main branch
          branch: data  # specifies the branch to merge from

      - name: Output PR details
        run: |
          echo "PR number: ${{ steps.cpr.outputs.pull-request-number }}"
          echo "PR URL: ${{ steps.cpr.outputs.pull-request-url }}"
